title = 'aetos.blog'
copyright = 'Copyright (c) 2026 - aetos'
defaultContentLanguage = 'ja'
locale = 'ja'
timeZone = 'Asia/Tokyo'
hasCJKLanguage = true
enableRobotsTXT = true
enableGitInfo = true
cleanDestinationDir = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[security]
  [security.exec]
    allow =[ '^asciidoctor$', '^git$', '^go$', '^sass$' ]
    osEnv = [ '(?i)^(PATH|GEM_PATH)$' ]

[markup]
  [markup.asciidocExt]
    extensions = ['asciidoctor-diagram', 'asciidoctor-hello']
    workingFolderCurrent = true
    [markup.asciidocExt.attributes]
      skip-front-matter = 'true'
      source-highlighter = 'rouge'

[params]
  custom_css = ['css/rouge.css']

[permalinks]
  post = '/post/:year/:month/:day/:contentbasename'
