author = 'aetos'
github = 'aetos382'
twitter = 'aetos382'
bluesky = 'aetos.me'
lastmod = true
rss = true
avatar = '/images/face-180.png'
headerIcon = '/images/blog-white-32.svg'
location = 'Saitama, Japan'
custom_css = ['css/rouge.css']
enableGitalk = true

[gitalk]
  clientID = 'Ov23liJZq7hid4IJeMGy'
  owner = 'aetos382'
  admin = 'aetos382'
  repo = 'aetos.blog'
  id = 'location.pathname'
  labels = 'gitalk'
  perPage = 10
  pagerDirection = 'last'
  createIssueManually = true
  distractionFreeMode = false
