baseURL = 'http://localhost:3000'
title = 'aetos.blog'
copyright = 'Copyright (c) 2026 - aetos'
defaultContentLanguage = 'ja'
locale = 'ja'
timeZone = 'Asia/Tokyo'
hasCJKLanguage = true
enableRobotsTXT = true
enableGitInfo = true
theme = 'github-style'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[security]
  [security.exec]
    allow =[ '^asciidoctor$', '^git$' ]
    osEnv = [ '(?i)^(PATH|GEM_PATH)$' ]

[markup]
  [markup.asciidocext]
    extensions = ['asciidoctor-diagram']
    workingFolderCurrent = true
    [markup.asciidocExt.attributes]
      source-highlighter = 'rouge'

[params]
  custom_css = ['css/rouge.css']

[permalinks]
  post = '/post/:year/:month/:day/:contentbasename'
