baseURL = 'http://localhost:3000'
defaultContentLanguage = 'ja'
locale = 'ja'
title = 'My New Hugo Project'
theme = 'github-style'
hasCJKLanguage = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[security]
  [security.exec]
    allow =[ '^asciidoctor$', '^git$' ]
    osEnv = [ '(?i)^(PATH|GEM_PATH)$' ]

[markup]
  [markup.asciidocext]
    extensions = ['asciidoctor-diagram']
    [markup.asciidocExt.attributes]
      source-highlighter = 'rouge'

[params]
  custom_css = ['css/rouge.css']
