name: publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      HUGO_VERSION: '0.160.1'
      DART_SASS_VERSION: '1.99.0'
      BUNDLE_GEMFILE: ${{ github.workspace }}/src/Gemfile
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
        id: pages

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'src/go.mod'

      - uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a # v1.302.0
        id: ruby
        with:
          ruby-version: '4.0.2'
          bundler-cache: true

      - run: |
          echo ${{ steps.ruby.outputs.ruby-prefix }}
          find / -name asciidoctor -type f

      - name: Prepare paths
        if: false
        run: |
          set -euo pipefail
          default_gem_paths="$(ruby -r rubygems -e 'puts Gem.default_path.join(":")')"
          echo "GEM_HOME=${HOME}/.gem" >> $GITHUB_ENV
          echo "GEM_PATH=${HOME}/.gem:${default_gem_paths}" >> $GITHUB_ENV
          echo "${HOME}/.gem/bin" >> $GITHUB_PATH

      - name: Install bundle
        if: false
        run: |
          set -euo pipefail
          bundle config set --global path.system true
          bundle install

      - name: Create bin directory
        run: |
          set -euo pipefail
          mkdir -p ${GITHUB_WORKSPACE}/bin
          echo "${GITHUB_WORKSPACE}/bin/" >> $GITHUB_PATH

      - name: Install Hugo
        run: |
          curl -qfsSL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.tar.gz -o hugo.tar.gz
          tar -C ${GITHUB_WORKSPACE}/bin/ -xzf hugo.tar.gz hugo
          rm hugo.tar.gz

      - name: Install Dart Sass
        run: |
          curl -qfsSL https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz -o dart-sass.tar.gz
          tar -C ${GITHUB_WORKSPACE}/bin/ -xzf dart-sass.tar.gz --strip-components=1
          rm dart-sass.tar.gz

      - name: Verify installations
        run: |
          set -euo pipefail
          echo "$PATH" | tr ':' '\n'
          hugo version | echo "hugo: $(cat -)"
          sass --version | echo "dart-sass: $(cat -)"
          asciidoctor --version | echo "asciidoctor: $(cat -)"
          go version | echo "go: $(cat -)"

      - name: Build
        working-directory: src
        run: >
          hugo build
          --baseURL ${{ steps.pages.outputs.base_url }}
          --environment production
          --minify

      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: 'src/public'

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
